# Generated by Django 5.2.17 on 2026-10-05 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importjob',
            name='mode',
            field=models.CharField(choices=[('add', 'Solo agregar nuevas'), ('update', 'Actualizar existentes'), ('both', 'Agregar y actualizar')], default='both', max_length=16),
        ),
    ]
