# Generated by Django 5.2.17 on 2026-10-05 21:09

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_importjob_mode'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='box',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='box_name_ci_unique'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='customer_name_ci_unique'),
        ),
        migrations.AddConstraint(
            model_name='destination',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='destination_name_ci_unique'),
        ),
        migrations.AddConstraint(
            model_name='sheetcolor',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='sheetcolor_name_ci_unique'),
        ),
    ]
